### ISSUE TITLE
Topluluk Dökümanlarının Çevirisi

### ISSUE THREAD

**Issue by WildGenie** [Kodluyoruz/discord-points-bot#8]
CODE_OF_CONDUCT ve CONTRIBUTING dosyalarının İngilizce versiyonu oluşturulacak.

**Comment by furkanulutas0** [comment]
> _No description provided._

CODE_OF_CONDUCT ve CONTRIBUTING dosyalarının İngilizce versiyonu oluşturulacak.

**Comment by furkanulutas0** [comment]
#27

**Comment by furkanulutas0** [comment]
#27 Issue done
